layout_spectrum: 0.8759524675551802
typography_spectrum: 0.5569118573330343
color:
  brandStrength: 0.14842282189056277
  lightness: 0.20622723805718124
  saturation: 0.23313259379938245
  rhythmicContrast: 0.27848745649680495
  brandColors:
    - '#000001'
    - '#021B31'
    - '#29507D'
    - '#627795'
    - '#788EB1'
name: Beta Nexus
